name: E2E Test

on:
  workflow_call:
    outputs:
      test_result:
        value: ${{ jobs.test.outputs.test_result }}

jobs:
  test:
    name: Playwright Test
    timeout-minutes: 60
    runs-on: ubuntu-latest
    outputs:
      test_result: ${{ steps.output.outputs.test_result }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: hyung-rae/end-to-end
          ref: main

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests (only template test)
        run: npm run test:template

      - name: Set output
        id: output
        run: echo "test_result=${{ job.status }}" >> $GITHUB_OUTPUT
